import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Landing from '../components/Landing'

import { useAuth } from '../contexts/authContext'
import { useEffect } from 'react'
import DashboardNav from '../components/dashboard/DashboardNav'

export default function Dashboard() {  

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <h1> */}
            {/* Welcome to Dashboard, {user.email}
            {console.log('User by dashboard ', user.email)}
            <button onClick={()=>{logout()}}>Logout</button> */}
            <DashboardNav/>
        {/* </h1> */}
      </main>
    </div>
  )
}
