import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Landing from '../components/Landing'

import { AiFillSetting } from 'react-icons/ai'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AiFillSetting/> */}
      <main className={styles.main}>
        <Landing/>
      </main>
    </div>
  )
}
