import dynamic from 'next/dynamic'
import Head from 'next/head'

const QrCode = dynamic(
    () => import('../components/QrCode'),
    { ssr: false }
)

function qr() {

    const url = "https://www.example.com"
  return (
    <div>
        <Head>
        <title>QR Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <QrCode url={url}/>
    </div>
  )
}

export default qr